### ISSUE TITLE
Page select (switch 0) commands not handled properly by VCEditor

### ISSUE THREAD

**Issue by deadtrickster** [sixeight7/VController_v3#4]
I have a page with two PC commands for page select. Editor breaks them - whenever I edit via editor the got mangled an even updateCommandsTableWidget is not updating.

Quick fix was this:

```
    /*if (sw > 0)*/ customLabel = read_title(pg, sw); // The label for switch 0 is the page name. We don't want to see that here.
```

I commented `if`. Reminds me classical off by one.

Here is debug output when `if` not commented:
```
Get cmd number for page: 3 switch:  0 and number: 1
first cmd index is 83
Command 83 loaded
set comboBoxWidget 0
set comboBoxWidget 1
set comboBoxWidget 2
set comboBoxWidget 3
set comboBoxWidget 6
onCurrentRowChanged 0
Get cmd number for page: 3 switch:  0 and number: 0
first cmd index is 83
Command 83 loaded
```

note for row 1 we load same command 83.

**Comment by sixeight7** [comment]
Thanks for pointing out the issue.

I fixed it in VCcommands::fillCommandTableWidget, where I changed the line

if ((switchHasLabel(pg, sw)) && (item > 0)) item--;

to

if ((switchHasLabel(pg, sw)) && (sw > 0) && (item > 0)) item--;
